% MAIN_RNE_FIXEDBASE  Fixed-base RNE torque computation for lifting task.
%
% Reads the joint trajectory from the Excel file generated by
% case5_lift_upward.m, runs the full Recursive Newton-Euler dynamic
% simulation, and saves results.
%
% OUTPUT files:
%   RNE_Fixedbase.mat           – tau, M, C, G for both arms
%   my_tau_outputsA/B.xlsx      – torque histories with timestamps
%   (plots auto-generated by exportAndPlotTau)

clc;
tic;

%% Load trajectory data
filename = 'Testoctlifting.xlsx';
fprintf('Loading trajectory from: %s\n', filename);
th_A     = readmatrix(filename,'Sheet',1).';
thdot_A  = readmatrix(filename,'Sheet',2).';
thddot_A = readmatrix(filename,'Sheet',3).';
th_B     = readmatrix(filename,'Sheet',4).';
thdot_B  = readmatrix(filename,'Sheet',5).';
thddot_B = readmatrix(filename,'Sheet',6).';

%% Object parameters (1 kg bottle-like object)
objParams.mass  = 1.056;                           % [kg]
objParams.I     = diag([0.00107, 0.05632, 0.05738]); % [kg·m²]
objParams.g_obj = [-9.81; 0; 0];                   % gravity in base frame

%% Run RNE — Arm A
fprintf('Running RNE for Arm A...\n');
[tau_A, M_A, C_A, G_A] = rnedynamicFixedBase1610(th_A,thdot_A,thddot_A,'A',objParams);

%% Run RNE — Arm B
fprintf('Running RNE for Arm B...\n');
[tau_B, M_B, C_B, G_B] = rnedynamicFixedBase1610(th_B,thdot_B,thddot_B,'B',objParams);

%% Save results
save('RNE_Fixedbase.mat','tau_A','M_A','C_A','G_A','tau_B','M_B','C_B','G_B');
fprintf('Results saved to RNE_Fixedbase.mat\n');

%% Display summary
fprintf('\nArm A – Joint Torques (first 3 samples):\n'); disp(tau_A(1:3,:));
fprintf('\nArm B – Joint Torques (first 3 samples):\n'); disp(tau_B(1:3,:));

%% Export and plot
exportAndPlotTau(tau_A, 0.01, 'my_tau_outputsA.xlsx', 'all', 'ArmA');
exportAndPlotTau(tau_B, 0.01, 'my_tau_outputsB.xlsx', 'all', 'ArmB');

fprintf('\nTotal elapsed: %.4f s\n', toc);
